create schema test_spring_boot_schema;

create table if not exists test_spring_boot_schema.entity_one
    (
        id bigint generated by default as identity
        primary key,
        col_1 varchar(255),
        col_2 integer,
        col_3 timestamp(6)
    );
